-- Create table for incomplete packages (without resident link)
CREATE TABLE public.encomendas_incompletas (
    id bigint generated by default as identity primary key,
    foto_url text, -- Optional photo if label is damaged/unclear
    descricao text, -- Description: "Caixa Amazon Grande"
    registrado_por text, -- Porteiro name/ID
    data_chegada timestamp with time zone default now(),
    status text default 'pendente' -- 'pendente', 'identificado'
);

-- RLS
ALTER TABLE public.encomendas_incompletas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for now" ON public.encomendas_incompletas FOR ALL USING (true);

-- No trigger needed, manual move via client logic
