-- 1. Tabela de Mensagens do Chat
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_role text not null check (sender_role in ('admin', 'porteiro')),
  sender_name text, -- Opcional, para exibir quem mandou
  content text not null,
  created_at timestamp with time zone default now(),
  read boolean default false
);

-- Index para ordenar por data
create index if not exists idx_chat_messages_created_at on public.chat_messages(created_at);

-- RLS: Permitir leitura e escrita para todos (simplificado para MVP, idealmente restrito por role)
alter table public.chat_messages enable row level security;

create policy "Todos podem ler mensagens"
on public.chat_messages for select
using (true);

create policy "Todos podem inserir mensagens"
on public.chat_messages for insert
with check (true);

-- 2. Tabela de Tokens dos Administradores
create table if not exists public.admin_notification_tokens (
  id bigint generated by default as identity primary key,
  admin_email text not null, -- Usando email como identificador pois loginAdmin usa email
  token text not null unique,
  updated_at timestamp with time zone default now()
);

alter table public.admin_notification_tokens enable row level security;

-- RPC para salvar token de admin
create or replace function save_admin_token(p_email text, p_token text)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.admin_notification_tokens (admin_email, token, updated_at)
  values (p_email, p_token, now())
  on conflict (token) do update
  set admin_email = p_email, updated_at = now();
end;
$$;

-- RPC para pegar TODOS os tokens de admin (para broadcast)
create or replace function get_all_admin_tokens()
returns table (token text)
language plpgsql
security definer
as $$
begin
  return query
  select t.token
  from public.admin_notification_tokens t;
end;
$$;

-- Realtime: Habilitar publicação de eventos na tabela de chat
alter publication supabase_realtime add table public.chat_messages;
