-- Create table for storing multiple tokens per user
create table if not exists public.notification_tokens (
  id bigint generated by default as identity primary key,
  morador_id bigint references public.moradores(id) on delete cascade not null,
  token text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint unique_token unique (token)
);

-- Index for faster lookups by user
create index if not exists idx_notification_tokens_morador_id on public.notification_tokens(morador_id);

-- Enable RLS
alter table public.notification_tokens enable row level security;

-- RPC Function to securely save token (bypassing RLS complexity for anon components)
create or replace function save_notification_token(p_user_id bigint, p_token text)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.notification_tokens (morador_id, token, updated_at)
  values (p_user_id, p_token, now())
  on conflict (token) do update
  set morador_id = p_user_id, updated_at = now();
end;
$$;

-- RPC Function to get all tokens for a user
create or replace function get_user_tokens(p_user_id bigint)
returns table (token text)
language plpgsql
security definer
as $$
begin
  return query
  select t.token
  from public.notification_tokens t
  where t.morador_id = p_user_id;
end;
$$;
